version: "3.8"
services:
  dev:
    container_name: salary-system-dev
    # image: salary-system-dev:0.0.1
    build:
      context: .
      target: development
      dockerfile: ./Dockerfile
    command: npm run start:dev
    ports:
        - 3000:3000
        - 9229:9229
    volumes:
        - .:/usr/src/app
        - /usr/src/app/node_modules
    env_file:
        - .env
    restart: unless-stopped
    depends_on:
        - postgres

  prod:
    container_name: salary-system-prod
    # image: salary-system-prod:1.0.0
    build:
        context: .
        target: production
        dockerfile: ./Dockerfile
    command: npm run start:prod
    ports:
        - 3001:3001
        - 9228:9228
    volumes:
        - .:/usr/src/app
        - /usr/src/app/node_modules
    env_file:
        - .env
    restart: unless-stopped
    depends_on:
        - postgres

  postgres:
    # container_name: postgres
    image: postgres:latest
    ports:
    - "5432:5432"
    volumes:
    - /data/postgres:/data/postgres
    env_file:
    - docker.env

  pgadmin:
    links:
    - postgres:postgres
    container_name: pgadmin
    image: dpage/pgadmin4
    ports:
    - "8080:80"
    volumes:
    - /data/pgadmin:/root/.pgadmin
    env_file:
    - docker.env